### ISSUE TITLE
IDaprSidecarHttpClientFactory.CreateInvokeHttpClient created HttpClient throws exception

### ISSUE THREAD

**Issue by helmerm** [man-group/dapr-sidekick-dotnet#32] opened 2021-10-29 12:24 UTC
## Expected Behavior

Perform service invocation via HTTP client created via IDaprSidecarHttpClientFactory.CreateInvokeHttpClient(appid);

## Actual Behavior

System.NullReferenceException: Object reference not set to an instance of an object.
at Man.Dapr.Sidekick.Http.HttpContextInvocationHandler.OnAfterSendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
at Man.Dapr.Sidekick.DaprClient.InvocationHandler.<SendAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

## Steps to Reproduce the Problem

Dapr 1.4
sidekick 1.2

```
                var daprClient = componentRegistration.ComponentHost.Services
                        .GetRequiredService<IDaprSidecarHttpClientFactory>();
                var appid = componentRegistration.DaprSidecarHost.GetProcessOptions().AppId;
                Debug.Assert(!string.IsNullOrEmpty(appid));
                using var http = daprClient.CreateInvokeHttpClient(appid);
                Debug.Assert(http != null);
                // 🧨🧨🧨
                var result = await http.GetAsync("testMethod");
```

## Release Note

RELEASE NOTE:
**FIX** Bug in IDaprSidecarHttpClientFactory.CreateInvokeHttpClient

**Comment by helmerm** [comment] 2021-10-29 20:31
I am using this inside my integration test setup, so it is hard to reproduce the same setup. For that I run multiple sidecars inside the same process and orchestrate some setup logic from my test setup.

After looking more into the code, I see that my understanding of how the DaprPort is retrieved was wrong. The IDaprSidecarHttpClientFactory does not use the ProcessOptions to look up the DaprPort of the sidecar. 
It uses the environment variable. This might cause some unexpected behavior in the InvocationHandler if the variable is not set.

I assume the NullReferenceException is a consecutive fault of the wrong DaprPort. Looking at the code, it only makes sense if the `request` is Null, since the [OnAfterSendAsync](https://github.com/man-group/dapr-sidekick-dotnet/blob/0fb8a6d256a6cedae8537958a34598ee9c1f5b0c/src/Man.Dapr.Sidekick/DaprClient/InvocationHandler.cs#L122) is called in the finally block.

**Comment by badgeratu** [comment] 2021-11-19 18:18
I think we can close this one, as I don't think there's a bug here. When Sidekick launches a Dapr sidecar it always sets the environment variable and the HTTP invocation client uses the same approach as the Dapr .NET SDK which also requires the environment variable, so provided its being used as intended it should work.

**Closed** 2021-11-19 18:20 UTC
